#Debug types: NORMAL, DEV/DEVELOPER
debug: 'DEV'

#This will be shown in the Authenticator App
use-playername: true

#Set the max tries that a player can use before getting kicked.
max-tries: 5

#Can the player switch servers while authenticating? (This is for server selectors)
switch-server: false

#Temp-ban will only work when you have a bungeecord ban plugin!
temp-ban: false
temp-ban-command: 'tempban <player> 1 hour &cToo many failed authentication attempts. (<tries>)'

#You can decide if you want the plugin to work via a players-list or permission
#For permission set the following to 'false'
use-player-list: true
permission: 'bungeeauth.2fa'

playerstorage:
    #Track the ip-address of every user that logs in that needs to have 2fa enabled
    track-ips: true
    #Should the player automatically be logged in when rejoining in a certain time
    auto-2fa: true
    #Time (in hours)
    time: 0.5
    #Should we use the login, or the logout to measure the time for relogging in a certain time?
    use: logout

#Data
players:
    - NTaheij
version: 1.0