#Debug types: OFF, NORMAL, DEV/DEVELOPER
debug: OFF

prefix: '&6BungeeAuth>>'

#This will be shown in the Authenticator app
auth-name: 'BungeeAuth'
use-playername: true

#Set the max tries that a player can use before getting kicked.
max-tries: 5
kick-message: '	&cYou have entered the code wrong &4" + tries_player + "&c times.'

#Temp-ban will only work when you have a bungeecord ban plugin!
temp-ban: false
temp-ban-command: 'tempban <player> 1 hour &cToo many failed authentication attempts. (<tries>)'

#You can decide if you want the plugin to work via a players-list or permission
#For permission set the following to 'false'
use-player-list: true
permission: 'bungeeauth.2fa'


#Data
players:
    - NTaheij
authcodes: